Update test-action.yml
test action

diff --git a/.github/workflows/test-action.yml b/.github/workflows/test-action.yml
--- a/.github/workflows/test-action.yml
+++ b/.github/workflows/test-action.yml
@@ -1,1 +1,24 @@
+name: Test Action
+on: [push]
 
+jobs:
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo to use the action locally
+        uses: actions/checkout@v4
+
+      - name: Run my own container action
+        id: my-action
+        uses: ./
+        with:
+          who-to-get: '@wulfland'
+
+      - name: Output the answer
+        run: echo "The anwser is ${{ steps.my-action.outout.answer }}"
+
+      - name: Test the container
+        if: ${{ steps.my-action.outouts.answer != 42 }}
+        run: |
+          echo "::error file=entrypoint.sh,line=4, title=Errpr in container::The answer was not expected"
+          exit 1
